CREATE TABLE Address (
    nameProvince nvarchar(max),
    nameDistrict nvarchar(max)
);


INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Hà Nội', N'Quận Ba Đình'),
(N'Hà Nội', N'Quận Hoàn Kiếm'),
(N'Hà Nội', N'Quận Tây Hồ'),
(N'Hà Nội', N'Quận Long Biên'),
(N'Hà Nội', N'Quận Cầu Giấy'),
(N'Hà Nội', N'Quận Đống Đa'),
(N'Hà Nội', N'Quận Hai Bà Trưng'),
(N'Hà Nội', N'Quận Hoàng Mai'),
(N'Hà Nội', N'Quận Thanh Xuân'),
(N'Hà Nội', N'Huyện Sóc Sơn'),
(N'Hà Nội', N'Huyện Đông Anh'),
(N'Hà Nội', N'Huyện Gia Lâm'),
(N'Hà Nội', N'Quận Nam Từ Liêm'),
(N'Hà Nội', N'Huyện Thanh Trì'),
(N'Hà Nội', N'Quận Bắc Từ Liêm'),
(N'Hà Nội', N'Huyện Mê Linh'),
(N'Hà Nội', N'Quận Hà Đông'),
(N'Hà Nội', N'Thị xã Sơn Tây'),
(N'Hà Nội', N'Huyện Ba Vì'),
(N'Hà Nội', N'Huyện Phúc Thọ'),
(N'Hà Nội', N'Huyện Đan Phượng'),
(N'Hà Nội', N'Huyện Hoài Đức'),
(N'Hà Nội', N'Huyện Quốc Oai'),
(N'Hà Nội', N'Huyện Thạch Thất'),
(N'Hà Nội', N'Huyện Chương Mỹ'),
(N'Hà Nội', N'Huyện Thanh Oai'),
(N'Hà Nội', N'Huyện Thường Tín'),
(N'Hà Nội', N'Huyện Phú Xuyên'),
(N'Hà Nội', N'Huyện Ứng Hòa'),
(N'Hà Nội', N'Huyện Mỹ Đức'),
-- Thêm dữ liệu cho Hà Giang
(N'Hà Giang', N'Thành phố Hà Giang'),
(N'Hà Giang', N'Huyện Đồng Văn'),
(N'Hà Giang', N'Huyện Mèo Vạc'),
(N'Hà Giang', N'Huyện Yên Minh'),
(N'Hà Giang', N'Huyện Quản Bạ'),
(N'Hà Giang', N'Huyện Vị Xuyên'),
(N'Hà Giang', N'Huyện Bắc Mê'),
(N'Hà Giang', N'Huyện Hoàng Su Phì'),
(N'Hà Giang', N'Huyện Xín Mần'),
(N'Hà Giang', N'Huyện Bắc Quang'),
(N'Hà Giang', N'Huyện Quang Bình'),
-- Thêm dữ liệu cho Cao Bằng
(N'Cao Bằng', N'Thành phố Cao Bằng'),
(N'Cao Bằng', N'Huyện Bảo Lâm'),
(N'Cao Bằng', N'Huyện Bảo Lạc'),
(N'Cao Bằng', N'Huyện Hà Quảng'),
(N'Cao Bằng', N'Huyện Trùng Khánh'),
(N'Cao Bằng', N'Huyện Hạ Lang'),
(N'Cao Bằng', N'Huyện Quảng Hòa'),
(N'Cao Bằng', N'Huyện Hoà An'),
(N'Cao Bằng', N'Huyện Nguyên Bình'),
(N'Cao Bằng', N'Huyện Thạch An'),
-- Thêm dữ liệu cho Bắc Kạn
(N'Bắc Kạn', N'Thành Phố Bắc Kạn'),
(N'Bắc Kạn', N'Huyện Pác Nặm'),
(N'Bắc Kạn', N'Huyện Ba Bể'),
(N'Bắc Kạn', N'Huyện Ngân Sơn'),
(N'Bắc Kạn', N'Huyện Bạch Thông'),
(N'Bắc Kạn', N'Huyện Chợ Đồn'),
(N'Bắc Kạn', N'Huyện Chợ Mới'),
(N'Bắc Kạn', N'Huyện Na Rì'),
-- Thêm dữ liệu cho Tuyên Quang
(N'Tuyên Quang', N'Thành phố Tuyên Quang'),
(N'Tuyên Quang', N'Huyện Lâm Bình'),
(N'Tuyên Quang', N'Huyện Na Hang'),
(N'Tuyên Quang', N'Huyện Chiêm Hóa'),
(N'Tuyên Quang', N'Huyện Hàm Yên'),
(N'Tuyên Quang', N'Huyện Yên Sơn'),
(N'Tuyên Quang', N'Huyện Sơn Dương');

-- Thêm dữ liệu cho Lào Cai
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Lào Cai', N'Thành phố Lào Cai'),
(N'Lào Cai', N'Huyện Bát Xát'),
(N'Lào Cai', N'Huyện Mường Khương'),
(N'Lào Cai', N'Huyện Si Ma Cai'),
(N'Lào Cai', N'Huyện Bắc Hà'),
(N'Lào Cai', N'Huyện Bảo Thắng'),
(N'Lào Cai', N'Huyện Bảo Yên'),
(N'Lào Cai', N'Thị xã Sa Pa'),
(N'Lào Cai', N'Huyện Văn Bàn'),
-- Thêm dữ liệu cho Điện Biên
(N'Điện Biên', N'Thành phố Điện Biên Phủ'),
(N'Điện Biên', N'Thị Xã Mường Lay'),
(N'Điện Biên', N'Huyện Mường Nhé'),
(N'Điện Biên', N'Huyện Mường Chà'),
(N'Điện Biên', N'Huyện Tủa Chùa'),
(N'Điện Biên', N'Huyện Tuần Giáo'),
(N'Điện Biên', N'Huyện Điện Biên'),
(N'Điện Biên', N'Huyện Điện Biên Đông'),
(N'Điện Biên', N'Huyện Mường Ảng'),
(N'Điện Biên', N'Huyện Nậm Pồ'),
-- Thêm dữ liệu cho Lai Châu
(N'Lai Châu', N'Thành phố Lai Châu'),
(N'Lai Châu', N'Huyện Tam Đường'),
(N'Lai Châu', N'Huyện Mường Tè'),
(N'Lai Châu', N'Huyện Sìn Hồ'),
(N'Lai Châu', N'Huyện Phong Thổ'),
(N'Lai Châu', N'Huyện Than Uyên'),
(N'Lai Châu', N'Huyện Tân Uyên'),
(N'Lai Châu', N'Huyện Nậm Nhùn'),
-- Thêm dữ liệu cho Sơn La
(N'Sơn La', N'Thành phố Sơn La'),
(N'Sơn La', N'Huyện Quỳnh Nhai'),
(N'Sơn La', N'Huyện Thuận Châu'),
(N'Sơn La', N'Huyện Mường La'),
(N'Sơn La', N'Huyện Bắc Yên'),
(N'Sơn La', N'Huyện Phù Yên'),
(N'Sơn La', N'Huyện Mộc Châu'),
(N'Sơn La', N'Huyện Yên Châu'),
(N'Sơn La', N'Huyện Mai Sơn'),
(N'Sơn La', N'Huyện Sông Mã'),
(N'Sơn La', N'Huyện Sốp Cộp'),
(N'Sơn La', N'Huyện Vân Hồ'),
-- Thêm dữ liệu cho Yên Bái
(N'Yên Bái', N'Thành phố Yên Bái'),
(N'Yên Bái', N'Thị xã Nghĩa Lộ'),
(N'Yên Bái', N'Huyện Lục Yên'),
(N'Yên Bái', N'Huyện Văn Yên'),
(N'Yên Bái', N'Huyện Mù Căng Chải'),
(N'Yên Bái', N'Huyện Trấn Yên'),
(N'Yên Bái', N'Huyện Trạm Tấu'),
(N'Yên Bái', N'Huyện Văn Chấn'),
(N'Yên Bái', N'Huyện Yên Bình'),
-- Thêm dữ liệu cho Hòa Bình
(N'Hòa Bình', N'Thành phố Hòa Bình'),
(N'Hòa Bình', N'Huyện Đà Bắc'),
(N'Hòa Bình', N'Huyện Lương Sơn'),
(N'Hòa Bình', N'Huyện Kim Bôi'),
(N'Hòa Bình', N'Huyện Cao Phong'),
(N'Hòa Bình', N'Huyện Tân Lạc'),
(N'Hòa Bình', N'Huyện Mai Châu'),
(N'Hòa Bình', N'Huyện Lạc Sơn'),
(N'Hòa Bình', N'Huyện Yên Thủy'),
(N'Hòa Bình', N'Huyện Lạc Thủy'),
-- Thêm dữ liệu cho Thái Nguyên
(N'Thái Nguyên', N'Thành phố Thái Nguyên'),
(N'Thái Nguyên', N'Thành phố Sông Công'),
(N'Thái Nguyên', N'Huyện Định Hóa'),
(N'Thái Nguyên', N'Huyện Phú Lương'),
(N'Thái Nguyên', N'Huyện Đồng Hỷ'),
(N'Thái Nguyên', N'Huyện Võ Nhai'),
(N'Thái Nguyên', N'Huyện Đại Từ'),
(N'Thái Nguyên', N'Thành phố Phổ Yên');
-- và tiếp tục với các tỉnh thành và quận huyện còn lại

-- Thêm dữ liệu cho Thái Nguyên
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Thái Nguyên', N'Huyện Phú Bình'),
-- Thêm dữ liệu cho Lạng Sơn
(N'Lạng Sơn', N'Thành phố Lạng Sơn'),
(N'Lạng Sơn', N'Huyện Tràng Định'),
(N'Lạng Sơn', N'Huyện Bình Gia'),
(N'Lạng Sơn', N'Huyện Văn Lãng'),
(N'Lạng Sơn', N'Huyện Cao Lộc'),
(N'Lạng Sơn', N'Huyện Văn Quan'),
(N'Lạng Sơn', N'Huyện Bắc Sơn'),
(N'Lạng Sơn', N'Huyện Hữu Lũng'),
(N'Lạng Sơn', N'Huyện Chi Lăng'),
(N'Lạng Sơn', N'Huyện Lộc Bình'),
(N'Lạng Sơn', N'Huyện Đình Lập'),
-- Thêm dữ liệu cho Quảng Ninh
(N'Quảng Ninh', N'Thành phố Hạ Long'),
(N'Quảng Ninh', N'Thành phố Móng Cái'),
(N'Quảng Ninh', N'Thành phố Cẩm Phả'),
(N'Quảng Ninh', N'Thành phố Uông Bí'),
(N'Quảng Ninh', N'Huyện Bình Liêu'),
(N'Quảng Ninh', N'Huyện Tiên Yên'),
(N'Quảng Ninh', N'Huyện Đầm Hà'),
(N'Quảng Ninh', N'Huyện Hải Hà'),
(N'Quảng Ninh', N'Huyện Ba Chẽ'),
(N'Quảng Ninh', N'Huyện Vân Đồn'),
(N'Quảng Ninh', N'Thị xã Đông Triều'),
(N'Quảng Ninh', N'Thị xã Quảng Yên'),
(N'Quảng Ninh', N'Huyện Cô Tô'),
-- Thêm dữ liệu cho Bắc Giang
(N'Bắc Giang', N'Thành phố Bắc Giang'),
(N'Bắc Giang', N'Huyện Yên Thế'),
(N'Bắc Giang', N'Huyện Tân Yên'),
(N'Bắc Giang', N'Huyện Lạng Giang'),
(N'Bắc Giang', N'Huyện Lục Nam'),
(N'Bắc Giang', N'Huyện Lục Ngạn'),
(N'Bắc Giang', N'Huyện Sơn Động'),
(N'Bắc Giang', N'Huyện Yên Dũng'),
(N'Bắc Giang', N'Huyện Việt Yên'),
(N'Bắc Giang', N'Huyện Hiệp Hòa');
-- và tiếp tục với các tỉnh thành và quận huyện còn lại

-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Phú Thọ', N'Thành phố Việt Trì'),
(N'Phú Thọ', N'Thị xã Phú Thọ'),
(N'Phú Thọ', N'Huyện Đoan Hùng'),
(N'Phú Thọ', N'Huyện Hạ Hoà'),
(N'Phú Thọ', N'Huyện Thanh Ba'),
(N'Phú Thọ', N'Huyện Phù Ninh'),
(N'Phú Thọ', N'Huyện Yên Lập'),
(N'Phú Thọ', N'Huyện Cẩm Khê'),
(N'Phú Thọ', N'Huyện Tam Nông'),
(N'Phú Thọ', N'Huyện Lâm Thao'),
(N'Phú Thọ', N'Huyện Thanh Sơn'),
(N'Phú Thọ', N'Huyện Thanh Thuỷ'),
(N'Phú Thọ', N'Huyện Tân Sơn'),
(N'Vĩnh Phúc', N'Thành phố Vĩnh Yên'),
(N'Vĩnh Phúc', N'Thành phố Phúc Yên'),
(N'Vĩnh Phúc', N'Huyện Lập Thạch'),
(N'Vĩnh Phúc', N'Huyện Tam Dương'),
(N'Vĩnh Phúc', N'Huyện Tam Đảo'),
(N'Vĩnh Phúc', N'Huyện Bình Xuyên'),
(N'Vĩnh Phúc', N'Huyện Yên Lạc'),
(N'Vĩnh Phúc', N'Huyện Vĩnh Tường'),
(N'Vĩnh Phúc', N'Huyện Sông Lô'),
(N'Bắc Ninh', N'Thành phố Bắc Ninh'),
(N'Bắc Ninh', N'Huyện Yên Phong'),
(N'Bắc Ninh', N'Huyện Quế Võ'),
(N'Bắc Ninh', N'Huyện Tiên Du'),
(N'Bắc Ninh', N'Thành phố Từ Sơn'),
(N'Bắc Ninh', N'Huyện Thuận Thành'),
(N'Bắc Ninh', N'Huyện Gia Bình'),
(N'Bắc Ninh', N'Huyện Lương Tài'),
(N'Hải Dương', N'Thành phố Hải Dương'),
(N'Hải Dương', N'Thành phố Chí Linh'),
(N'Hải Dương', N'Huyện Nam Sách'),
(N'Hải Dương', N'Thị xã Kinh Môn'),
(N'Hải Dương', N'Huyện Kim Thành'),
(N'Hải Dương', N'Huyện Thanh Hà'),
(N'Hải Dương', N'Huyện Cẩm Giàng'),
(N'Hải Dương', N'Huyện Bình Giang'),
(N'Hải Dương', N'Huyện Gia Lộc'),
(N'Hải Dương', N'Huyện Tứ Kỳ'),
(N'Hải Dương', N'Huyện Ninh Giang'),
(N'Hải Dương', N'Huyện Thanh Miện');

-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Hải Phòng', N'Quận Hồng Bàng'),
(N'Hải Phòng', N'Quận Ngô Quyền'),
(N'Hải Phòng', N'Quận Lê Chân'),
(N'Hải Phòng', N'Quận Hải An'),
(N'Hải Phòng', N'Quận Kiến An'),
(N'Hải Phòng', N'Quận Đồ Sơn'),
(N'Hải Phòng', N'Quận Dương Kinh'),
(N'Hải Phòng', N'Huyện Thuỷ Nguyên'),
(N'Hải Phòng', N'Huyện An Dương'),
(N'Hải Phòng', N'Huyện An Lão'),
(N'Hải Phòng', N'Huyện Kiến Thuỵ'),
(N'Hải Phòng', N'Huyện Tiên Lãng'),
(N'Hải Phòng', N'Huyện Vĩnh Bảo'),
(N'Hải Phòng', N'Huyện Cát Hải'),
(N'Hải Phòng', N'Huyện Bạch Long Vĩ'),
(N'Hưng Yên', N'Thành phố Hưng Yên'),
(N'Hưng Yên', N'Huyện Văn Lâm'),
(N'Hưng Yên', N'Huyện Văn Giang'),
(N'Hưng Yên', N'Huyện Yên Mỹ'),
(N'Hưng Yên', N'Thị xã Mỹ Hào'),
(N'Hưng Yên', N'Huyện Ân Thi'),
(N'Hưng Yên', N'Huyện Khoái Châu'),
(N'Hưng Yên', N'Huyện Kim Động'),
(N'Hưng Yên', N'Huyện Tiên Lữ'),
(N'Hưng Yên', N'Huyện Phù Cừ'),
(N'Thái Bình', N'Thành phố Thái Bình'),
(N'Thái Bình', N'Huyện Quỳnh Phụ'),
(N'Thái Bình', N'Huyện Hưng Hà'),
(N'Thái Bình', N'Huyện Đông Hưng'),
(N'Thái Bình', N'Huyện Thái Thụy'),
(N'Thái Bình', N'Huyện Tiền Hải'),
(N'Thái Bình', N'Huyện Kiến Xương'),
(N'Thái Bình', N'Huyện Vũ Thư'),
(N'Hà Nam', N'Thành phố Phủ Lý'),
(N'Hà Nam', N'Thị xã Duy Tiên'),
(N'Hà Nam', N'Huyện Kim Bảng'),
(N'Hà Nam', N'Huyện Thanh Liêm'),
(N'Hà Nam', N'Huyện Bình Lục'),
(N'Hà Nam', N'Huyện Lý Nhân'),
(N'Nam Định', N'Thành phố Nam Định'),
(N'Nam Định', N'Huyện Mỹ Lộc'),
(N'Nam Định', N'Huyện Vụ Bản'),
(N'Nam Định', N'Huyện Ý Yên'),
(N'Nam Định', N'Huyện Nghĩa Hưng'),
(N'Nam Định', N'Huyện Nam Trực'),
(N'Nam Định', N'Huyện Trực Ninh'),
(N'Nam Định', N'Huyện Xuân Trường'),
(N'Nam Định', N'Huyện Giao Thủy'),
(N'Nam Định', N'Huyện Hải Hậu');


-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Ninh Bình', N'Thành phố Ninh Bình'),
(N'Ninh Bình', N'Thành phố Tam Điệp'),
(N'Ninh Bình', N'Huyện Nho Quan'),
(N'Ninh Bình', N'Huyện Gia Viễn'),
(N'Ninh Bình', N'Huyện Hoa Lư'),
(N'Ninh Bình', N'Huyện Yên Khánh'),
(N'Ninh Bình', N'Huyện Kim Sơn'),
(N'Ninh Bình', N'Huyện Yên Mô'),
(N'Thanh Hóa', N'Thành phố Thanh Hóa'),
(N'Thanh Hóa', N'Thị xã Bỉm Sơn'),
(N'Thanh Hóa', N'Thành phố Sầm Sơn'),
(N'Thanh Hóa', N'Huyện Mường Lát'),
(N'Thanh Hóa', N'Huyện Quan Hóa'),
(N'Thanh Hóa', N'Huyện Bá Thước'),
(N'Thanh Hóa', N'Huyện Quan Sơn'),
(N'Thanh Hóa', N'Huyện Lang Chánh'),
(N'Thanh Hóa', N'Huyện Ngọc Lặc'),
(N'Thanh Hóa', N'Huyện Cẩm Thủy'),
(N'Thanh Hóa', N'Huyện Thạch Thành'),
(N'Thanh Hóa', N'Huyện Hà Trung'),
(N'Thanh Hóa', N'Huyện Vĩnh Lộc'),
(N'Thanh Hóa', N'Huyện Yên Định'),
(N'Thanh Hóa', N'Huyện Thọ Xuân'),
(N'Thanh Hóa', N'Huyện Thường Xuân'),
(N'Thanh Hóa', N'Huyện Triệu Sơn'),
(N'Thanh Hóa', N'Huyện Thiệu Hóa'),
(N'Thanh Hóa', N'Huyện Hoằng Hóa'),
(N'Thanh Hóa', N'Huyện Hậu Lộc'),
(N'Thanh Hóa', N'Huyện Nga Sơn'),
(N'Thanh Hóa', N'Huyện Như Xuân'),
(N'Thanh Hóa', N'Huyện Như Thanh'),
(N'Thanh Hóa', N'Huyện Nông Cống'),
(N'Thanh Hóa', N'Huyện Đông Sơn'),
(N'Thanh Hóa', N'Huyện Quảng Xương'),
(N'Thanh Hóa', N'Thị xã Nghi Sơn'),
(N'Nghệ An', N'Thành phố Vinh'),
(N'Nghệ An', N'Thị xã Cửa Lò'),
(N'Nghệ An', N'Thị xã Thái Hoà'),
(N'Nghệ An', N'Huyện Quế Phong'),
(N'Nghệ An', N'Huyện Quỳ Châu'),
(N'Nghệ An', N'Huyện Kỳ Sơn'),
(N'Nghệ An', N'Huyện Tương Dương'),
(N'Nghệ An', N'Huyện Nghĩa Đàn'),
(N'Nghệ An', N'Huyện Quỳ Hợp'),
(N'Nghệ An', N'Huyện Quỳnh Lưu'),
(N'Nghệ An', N'Huyện Con Cuông'),
(N'Nghệ An', N'Huyện Tân Kỳ'),
(N'Nghệ An', N'Huyện Anh Sơn'),
(N'Nghệ An', N'Huyện Diễn Châu'),
(N'Nghệ An', N'Huyện Yên Thành'),
(N'Nghệ An', N'Huyện Đô Lương'),
(N'Nghệ An', N'Huyện Thanh Chương'),
(N'Nghệ An', N'Huyện Nghi Lộc'),
(N'Nghệ An', N'Huyện Nam Đàn'),
(N'Nghệ An', N'Huyện Hưng Nguyên'),
(N'Nghệ An', N'Thị xã Hoàng Mai');

-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Hà Tĩnh', N'Thành phố Hà Tĩnh'),
(N'Hà Tĩnh', N'Thị xã Hồng Lĩnh'),
(N'Hà Tĩnh', N'Huyện Hương Sơn'),
(N'Hà Tĩnh', N'Huyện Đức Thọ'),
(N'Hà Tĩnh', N'Huyện Vũ Quang'),
(N'Hà Tĩnh', N'Huyện Nghi Xuân'),
(N'Hà Tĩnh', N'Huyện Can Lộc'),
(N'Hà Tĩnh', N'Huyện Hương Khê'),
(N'Hà Tĩnh', N'Huyện Thạch Hà'),
(N'Hà Tĩnh', N'Huyện Cẩm Xuyên'),
(N'Hà Tĩnh', N'Huyện Kỳ Anh'),
(N'Hà Tĩnh', N'Huyện Lộc Hà'),
(N'Hà Tĩnh', N'Thị xã Kỳ Anh'),
(N'Quảng Bình', N'Thành Phố Đồng Hới'),
(N'Quảng Bình', N'Huyện Minh Hóa'),
(N'Quảng Bình', N'Huyện Tuyên Hóa'),
(N'Quảng Bình', N'Huyện Quảng Trạch'),
(N'Quảng Bình', N'Huyện Bố Trạch'),
(N'Quảng Bình', N'Huyện Quảng Ninh'),
(N'Quảng Bình', N'Huyện Lệ Thủy'),
(N'Quảng Bình', N'Thị xã Ba Đồn'),
(N'Quảng Trị', N'Thành phố Đông Hà'),
(N'Quảng Trị', N'Thị xã Quảng Trị'),
(N'Quảng Trị', N'Huyện Vĩnh Linh'),
(N'Quảng Trị', N'Huyện Hướng Hóa'),
(N'Quảng Trị', N'Huyện Gio Linh'),
(N'Quảng Trị', N'Huyện Đa Krông'),
(N'Quảng Trị', N'Huyện Cam Lộ'),
(N'Quảng Trị', N'Huyện Triệu Phong'),
(N'Quảng Trị', N'Huyện Hải Lăng'),
(N'Quảng Trị', N'Huyện Cồn Cỏ'),
(N'Thừa Thiên-Huế', N'Thành phố Huế'),
(N'Thừa Thiên-Huế', N'Huyện Phong Điền'),
(N'Thừa Thiên-Huế', N'Huyện Quảng Điền'),
(N'Thừa Thiên-Huế', N'Huyện Phú Vang'),
(N'Thừa Thiên-Huế', N'Thị xã Hương Thủy'),
(N'Thừa Thiên-Huế', N'Thị xã Hương Trà'),
(N'Thừa Thiên-Huế', N'Huyện A Lưới'),
(N'Thừa Thiên-Huế', N'Huyện Phú Lộc'),
(N'Thừa Thiên-Huế', N'Huyện Nam Đông'),
(N'Đà Nẵng', N'Quận Liên Chiểu'),
(N'Đà Nẵng', N'Quận Thanh Khê'),
(N'Đà Nẵng', N'Quận Hải Châu'),
(N'Đà Nẵng', N'Quận Sơn Trà'),
(N'Đà Nẵng', N'Quận Ngũ Hành Sơn'),
(N'Đà Nẵng', N'Quận Cẩm Lệ'),
(N'Đà Nẵng', N'Huyện Hòa Vang'),
(N'Đà Nẵng', N'Huyện Hoàng Sa'),
(N'Quảng Nam', N'Thành phố Tam Kỳ'),
(N'Quảng Nam', N'Thành phố Hội An'),
(N'Quảng Nam', N'Huyện Tây Giang'),
(N'Quảng Nam', N'Huyện Đông Giang'),
(N'Quảng Nam', N'Huyện Đại Lộc'),
(N'Quảng Nam', N'Thị xã Điện Bàn'),
(N'Quảng Nam', N'Huyện Duy Xuyên'),
(N'Quảng Nam', N'Huyện Quế Sơn'),
(N'Quảng Nam', N'Huyện Nam Giang'),
(N'Quảng Nam', N'Huyện Phước Sơn'),
(N'Quảng Nam', N'Huyện Hiệp Đức'),
(N'Quảng Nam', N'Huyện Thăng Bình'),
(N'Quảng Nam', N'Huyện Tiên Phước'),
(N'Quảng Nam', N'Huyện Bắc Trà My'),
(N'Quảng Nam', N'Huyện Nam Trà My'),
(N'Quảng Nam', N'Huyện Núi Thành'),
(N'Quảng Nam', N'Huyện Phú Ninh'),
(N'Quảng Nam', N'Huyện Nông Sơn'),
(N'Quảng Ngãi', N'Thành phố Quảng Ngãi'),
(N'Quảng Ngãi', N'Huyện Bình Sơn'),
(N'Quảng Ngãi', N'Huyện Trà Bồng'),
(N'Quảng Ngãi', N'Huyện Sơn Tịnh'),
(N'Quảng Ngãi', N'Huyện Tư Nghĩa'),
(N'Quảng Ngãi', N'Huyện Sơn Hà'),
(N'Quảng Ngãi', N'Huyện Sơn Tây'),
(N'Quảng Ngãi', N'Huyện Minh Long'),
(N'Quảng Ngãi', N'Huyện Nghĩa Hành'),
(N'Quảng Ngãi', N'Huyện Mộ Đức'),
(N'Quảng Ngãi', N'Thị xã Đức Phổ'),
(N'Quảng Ngãi', N'Huyện Ba Tơ'),
(N'Quảng Ngãi', N'Huyện Lý Sơn');



-- Thêm dữ liệu vào bảng Address
-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Bình Định', N'Thị xã Hoài Nhơn'),
(N'Bình Định', N'Huyện Hoài Ân'),
(N'Bình Định', N'Huyện Phù Mỹ'),
(N'Bình Định', N'Huyện Vĩnh Thạnh'),
(N'Bình Định', N'Huyện Tây Sơn'),
(N'Bình Định', N'Huyện Phù Cát'),
(N'Bình Định', N'Thị xã An Nhơn'),
(N'Bình Định', N'Huyện Tuy Phước'),
(N'Bình Định', N'Huyện Vân Canh'),
(N'Phú Yên', N'Thành phố Tuy Hoà'),
(N'Phú Yên', N'Thị xã Sông Cầu'),
(N'Phú Yên', N'Huyện Đồng Xuân'),
(N'Phú Yên', N'Huyện Tuy An'),
(N'Phú Yên', N'Huyện Sơn Hòa'),
(N'Phú Yên', N'Huyện Sông Hinh'),
(N'Phú Yên', N'Huyện Tây Hoà'),
(N'Phú Yên', N'Huyện Phú Hoà'),
(N'Phú Yên', N'Thị xã Đông Hòa'),
(N'Khánh Hòa', N'Thành phố Nha Trang'),
(N'Khánh Hòa', N'Thành phố Cam Ranh'),
(N'Khánh Hòa', N'Huyện Cam Lâm'),
(N'Khánh Hòa', N'Huyện Vạn Ninh'),
(N'Khánh Hòa', N'Thị xã Ninh Hòa'),
(N'Khánh Hòa', N'Huyện Khánh Vĩnh'),
(N'Khánh Hòa', N'Huyện Diên Khánh'),
(N'Khánh Hòa', N'Huyện Khánh Sơn'),
(N'Khánh Hòa', N'Huyện Trường Sa'),
(N'Ninh Thuận', N'Thành phố Phan Rang-Tháp Chàm'),
(N'Ninh Thuận', N'Huyện Bác Ái'),
(N'Ninh Thuận', N'Huyện Ninh Sơn'),
(N'Ninh Thuận', N'Huyện Ninh Hải'),
(N'Ninh Thuận', N'Huyện Ninh Phước'),
(N'Ninh Thuận', N'Huyện Thuận Bắc'),
(N'Ninh Thuận', N'Huyện Thuận Nam'),
(N'Bình Thuận', N'Thành phố Phan Thiết'),
(N'Bình Thuận', N'Thị xã La Gi'),
(N'Bình Thuận', N'Huyện Tuy Phong'),
(N'Bình Thuận', N'Huyện Bắc Bình'),
(N'Bình Thuận', N'Huyện Hàm Thuận Bắc'),
(N'Bình Thuận', N'Huyện Hàm Thuận Nam'),
(N'Bình Thuận', N'Huyện Tánh Linh'),
(N'Bình Thuận', N'Huyện Đức Linh'),
(N'Bình Thuận', N'Huyện Hàm Tân'),
(N'Bình Thuận', N'Huyện Phú Quí'),
(N'Kon Tum', N'Thành phố Kon Tum'),
(N'Kon Tum', N'Huyện Đắk Glei'),
(N'Kon Tum', N'Huyện Ngọc Hồi'),
(N'Kon Tum', N'Huyện Đắk Tô'),
(N'Kon Tum', N'Huyện Kon Plông'),
(N'Kon Tum', N'Huyện Kon Rẫy'),
(N'Kon Tum', N'Huyện Đắk Hà'),
(N'Kon Tum', N'Huyện Sa Thầy'),
(N'Kon Tum', N'Huyện Tu Mơ Rông'),
(N'Kon Tum', N'Huyện Ia H'' Drai'),
(N'Gia Lai', N'Thành phố Pleiku'),
(N'Gia Lai', N'Thị xã An Khê'),
(N'Gia Lai', N'Thị xã Ayun Pa'),
(N'Gia Lai', N'Huyện KBang'),
(N'Gia Lai', N'Huyện Đăk Đoa'),
(N'Gia Lai', N'Huyện Chư Păh'),
(N'Gia Lai', N'Huyện Ia Grai'),
(N'Gia Lai', N'Huyện Mang Yang'),
(N'Gia Lai', N'Huyện Kông Chro'),
(N'Gia Lai', N'Huyện Đức Cơ'),
(N'Gia Lai', N'Huyện Chư Prông'),
(N'Gia Lai', N'Huyện Chư Sê'),
(N'Gia Lai', N'Huyện Đắk Pơ'),
(N'Gia Lai', N'Huyện Ia Pa'),
(N'Gia Lai', N'Huyện Krông Pa'),
(N'Gia Lai', N'Huyện Phú Thiện'),
(N'Gia Lai', N'Huyện Chư Pưh');

-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Đắk Lắk', N'Thành phố Buôn Ma Thuột'),
(N'Đắk Lắk', N'Thị Xã Buôn Hồ'),
(N'Đắk Lắk', N'Huyện Ea Hleo'),
(N'Đắk Lắk', N'Huyện Ea Súp'),
(N'Đắk Lắk', N'Huyện Buôn Đôn'),
(N'Đắk Lắk', N'Huyện Cư Mgar'),
(N'Đắk Lắk', N'Huyện Krông Búk'),
(N'Đắk Lắk', N'Huyện Krông Năng'),
(N'Đắk Lắk', N'Huyện Ea Kar'),
(N'Đắk Lắk', N'Huyện MĐrắk'),
(N'Đắk Lắk', N'Huyện Krông Bông'),
(N'Đắk Lắk', N'Huyện Krông Pắc'),
(N'Đắk Lắk', N'Huyện Krông A Na'),
(N'Đắk Lắk', N'Huyện Lắk'),
(N'Đắk Lắk', N'Huyện Cư Kuin'),
(N'Đắk Nông', N'Thành phố Gia Nghĩa'),
(N'Đắk Nông', N'Huyện Đăk Glong'),
(N'Đắk Nông', N'Huyện Cư Jút'),
(N'Đắk Nông', N'Huyện Đắk Mil'),
(N'Đắk Nông', N'Huyện Krông Nô'),
(N'Đắk Nông', N'Huyện Đắk Song'),
(N'Đắk Nông', N'Huyện Đắk RLấp'),
(N'Đắk Nông', N'Huyện Tuy Đức'),
(N'Lâm Đồng', N'Thành phố Đà Lạt'),
(N'Lâm Đồng', N'Thành phố Bảo Lộc'),
(N'Lâm Đồng', N'Huyện Đam Rông'),
(N'Lâm Đồng', N'Huyện Lạc Dương'),
(N'Lâm Đồng', N'Huyện Lâm Hà'),
(N'Lâm Đồng', N'Huyện Đơn Dương'),
(N'Lâm Đồng', N'Huyện Đức Trọng'),
(N'Lâm Đồng', N'Huyện Di Linh'),
(N'Lâm Đồng', N'Huyện Bảo Lâm'),
(N'Lâm Đồng', N'Huyện Đạ Huoai'),
(N'Lâm Đồng', N'Huyện Đạ Tẻh'),
(N'Lâm Đồng', N'Huyện Cát Tiên'),
(N'Bình Phước', N'Thị xã Phước Long'),
(N'Bình Phước', N'Thành phố Đồng Xoài'),
(N'Bình Phước', N'Thị xã Bình Long'),
(N'Bình Phước', N'Huyện Bù Gia Mập'),
(N'Bình Phước', N'Huyện Lộc Ninh'),
(N'Bình Phước', N'Huyện Bù Đốp'),
(N'Bình Phước', N'Huyện Hớn Quản'),
(N'Bình Phước', N'Huyện Đồng Phú'),
(N'Bình Phước', N'Huyện Bù Đăng'),
(N'Bình Phước', N'Huyện Chơn Thành'),
(N'Bình Phước', N'Huyện Phú Riềng'),
(N'Tây Ninh', N'Thành phố Tây Ninh'),
(N'Tây Ninh', N'Huyện Tân Biên'),
(N'Tây Ninh', N'Huyện Tân Châu'),
(N'Tây Ninh', N'Huyện Dương Minh Châu'),
(N'Tây Ninh', N'Huyện Châu Thành'),
(N'Tây Ninh', N'Thị xã Hòa Thành'),
(N'Tây Ninh', N'Huyện Gò Dầu'),
(N'Tây Ninh', N'Huyện Bến Cầu'),
(N'Tây Ninh', N'Thị xã Trảng Bàng'),
(N'Bình Dương', N'Thành phố Thủ Dầu Một'),
(N'Bình Dương', N'Huyện Bàu Bàng'),
(N'Bình Dương', N'Huyện Dầu Tiếng'),
(N'Bình Dương', N'Thị xã Bến Cát'),
(N'Bình Dương', N'Huyện Phú Giáo'),
(N'Bình Dương', N'Thị xã Tân Uyên'),
(N'Bình Dương', N'Thành phố Dĩ An'),
(N'Bình Dương', N'Thành phố Thuận An'),
(N'Bình Dương', N'Huyện Bắc Tân Uyên'),
(N'Đồng Nai', N'Thành phố Biên Hòa'),
(N'Đồng Nai', N'Thành phố Long Khánh'),
(N'Đồng Nai', N'Huyện Tân Phú'),
(N'Đồng Nai', N'Huyện Vĩnh Cửu'),
(N'Đồng Nai', N'Huyện Định Quán'),
(N'Đồng Nai', N'Huyện Trảng Bom'),
(N'Đồng Nai', N'Huyện Thống Nhất'),
(N'Đồng Nai', N'Huyện Cẩm Mỹ'),
(N'Đồng Nai', N'Huyện Long Thành'),
(N'Đồng Nai', N'Huyện Xuân Lộc'),
(N'Bà Rịa-Vũng Tàu', N'Thành phố Vũng Tàu'),
(N'Bà Rịa-Vũng Tàu', N'Thành phố Bà Rịa'),
(N'Bà Rịa-Vũng Tàu', N'Huyện Châu Đức'),
(N'Bà Rịa-Vũng Tàu', N'Huyện Xuyên Mộc'),
(N'Bà Rịa-Vũng Tàu', N'Huyện Long Điền'),
(N'Bà Rịa-Vũng Tàu', N'Huyện Đất Đỏ'),
(N'Bà Rịa-Vũng Tàu', N'Thị xã Phú Mỹ'),
(N'Bà Rịa-Vũng Tàu', N'Huyện Côn Đảo');


-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'Hồ Chí Minh', N'Quận 1'),
(N'Hồ Chí Minh', N'Quận 12'),
(N'Hồ Chí Minh', N'Quận Gò Vấp'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh'),
(N'Hồ Chí Minh', N'Quận Tân Bình'),
(N'Hồ Chí Minh', N'Quận Tân Phú'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận'),
(N'Hồ Chí Minh', N'Thành phố Thủ Đức'),
(N'Hồ Chí Minh', N'Quận 3'),
(N'Hồ Chí Minh', N'Quận 10'),
(N'Hồ Chí Minh', N'Quận 11'),
(N'Hồ Chí Minh', N'Quận 4'),
(N'Hồ Chí Minh', N'Quận 5'),
(N'Hồ Chí Minh', N'Quận 6'),
(N'Hồ Chí Minh', N'Quận 8'),
(N'Hồ Chí Minh', N'Quận Bình Tân'),
(N'Hồ Chí Minh', N'Quận 7'),
(N'Hồ Chí Minh', N'Huyện Củ Chi'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ'),
(N'Long An', N'Thành phố Tân An'),
(N'Long An', N'Thị xã Kiến Tường'),
(N'Long An', N'Huyện Tân Hưng'),
(N'Long An', N'Huyện Vĩnh Hưng'),
(N'Long An', N'Huyện Mộc Hóa'),
(N'Long An', N'Huyện Tân Thạnh'),
(N'Long An', N'Huyện Thạnh Hóa'),
(N'Long An', N'Huyện Đức Huệ'),
(N'Long An', N'Huyện Đức Hòa'),
(N'Long An', N'Huyện Bến Lức'),
(N'Long An', N'Huyện Thủ Thừa'),
(N'Long An', N'Huyện Tân Trụ'),
(N'Long An', N'Huyện Cần Đước'),
(N'Long An', N'Huyện Cần Giuộc'),
(N'Tiền Giang', N'Thành phố Mỹ Tho'),
(N'Tiền Giang', N'Thị xã Gò Công'),
(N'Tiền Giang', N'Thị xã Cai Lậy'),
(N'Tiền Giang', N'Huyện Tân Phước'),
(N'Tiền Giang', N'Huyện Cái Bè'),
(N'Tiền Giang', N'Huyện Cai Lậy'),
(N'Tiền Giang', N'Huyện Châu Thành'),
(N'Tiền Giang', N'Huyện Chợ Gạo'),
(N'Tiền Giang', N'Huyện Gò Công Tây'),
(N'Tiền Giang', N'Huyện Gò Công Đông'),
(N'Tiền Giang', N'Huyện Tân Phú Đông'),
(N'Bến Tre', N'Thành phố Bến Tre'),
(N'Bến Tre', N'Huyện Châu Thành'),
(N'Bến Tre', N'Huyện Chợ Lách'),
(N'Bến Tre', N'Huyện Mỏ Cày Nam'),
(N'Bến Tre', N'Huyện Giồng Trôm'),
(N'Bến Tre', N'Huyện Bình Đại'),
(N'Bến Tre', N'Huyện Ba Tri'),
(N'Bến Tre', N'Huyện Thạnh Phú'),
(N'Bến Tre', N'Huyện Mỏ Cày Bắc'),
(N'Trà Vinh', N'Thành phố Trà Vinh'),
(N'Trà Vinh', N'Huyện Càng Long'),
(N'Trà Vinh', N'Huyện Cầu Kè'),
(N'Trà Vinh', N'Huyện Tiểu Cần'),
(N'Trà Vinh', N'Huyện Châu Thành'),
(N'Trà Vinh', N'Huyện Cầu Ngang'),
(N'Trà Vinh', N'Huyện Trà Cú'),
(N'Trà Vinh', N'Huyện Duyên Hải'),
(N'Trà Vinh', N'Thị xã Duyên Hải'),
(N'Vĩnh Long', N'Thành phố Vĩnh Long'),
(N'Vĩnh Long', N'Huyện Long Hồ'),
(N'Vĩnh Long', N'Huyện Mang Thít'),
(N'Vĩnh Long', N'Huyện Vũng Liêm'),
(N'Vĩnh Long', N'Huyện Tam Bình'),
(N'Vĩnh Long', N'Thị xã Bình Minh'),
(N'Vĩnh Long', N'Huyện Trà Ôn'),
(N'Vĩnh Long', N'Huyện Bình Tân'),
(N'Đồng Tháp', N'Thành phố Cao Lãnh'),
(N'Đồng Tháp', N'Thành phố Sa Đéc'),
(N'Đồng Tháp', N'Thành phố Hồng Ngự'),
(N'Đồng Tháp', N'Huyện Tân Hồng'),
(N'Đồng Tháp', N'Huyện Hồng Ngự'),
(N'Đồng Tháp', N'Huyện Tam Nông'),
(N'Đồng Tháp', N'Huyện Tháp Mười'),
(N'Đồng Tháp', N'Huyện Cao Lãnh'),
(N'Đồng Tháp', N'Huyện Thanh Bình'),
(N'Đồng Tháp', N'Huyện Lấp Vò'),
(N'Đồng Tháp', N'Huyện Lai Vung'),
(N'Đồng Tháp', N'Huyện Châu Thành');

-- Thêm dữ liệu vào bảng Address
INSERT INTO Address (nameProvince, nameDistrict)
VALUES
(N'An Giang', N'Thành phố Long Xuyên'),
(N'An Giang', N'Thành phố Châu Đốc'),
(N'An Giang', N'Huyện An Phú'),
(N'An Giang', N'Thị xã Tân Châu'),
(N'An Giang', N'Huyện Phú Tân'),
(N'An Giang', N'Huyện Châu Phú'),
(N'An Giang', N'Huyện Tịnh Biên'),
(N'An Giang', N'Huyện Tri Tôn'),
(N'An Giang', N'Huyện Châu Thành'),
(N'An Giang', N'Huyện Chợ Mới'),
(N'An Giang', N'Huyện Thoại Sơn'),
(N'Kiên Giang', N'Thành phố Rạch Giá'),
(N'Kiên Giang', N'Thành phố Hà Tiên'),
(N'Kiên Giang', N'Huyện Kiên Lương'),
(N'Kiên Giang', N'Huyện Hòn Đất'),
(N'Kiên Giang', N'Huyện Tân Hiệp'),
(N'Kiên Giang', N'Huyện Châu Thành'),
(N'Kiên Giang', N'Huyện Giồng Riềng'),
(N'Kiên Giang', N'Huyện Gò Quao'),
(N'Kiên Giang', N'Huyện An Biên'),
(N'Kiên Giang', N'Huyện An Minh'),
(N'Kiên Giang', N'Huyện Vĩnh Thuận'),
(N'Kiên Giang', N'Thành phố Phú Quốc'),
(N'Kiên Giang', N'Huyện Kiên Hải'),
(N'Kiên Giang', N'Huyện U Minh Thượng'),
(N'Kiên Giang', N'Huyện Giang Thành'),
(N'Cần Thơ', N'Quận Ninh Kiều'),
(N'Cần Thơ', N'Quận Ô Môn'),
(N'Cần Thơ', N'Quận Bình Thuỷ'),
(N'Cần Thơ', N'Quận Cái Răng'),
(N'Cần Thơ', N'Quận Thốt Nốt'),
(N'Cần Thơ', N'Huyện Vĩnh Thạnh'),
(N'Cần Thơ', N'Huyện Cờ Đỏ'),
(N'Cần Thơ', N'Huyện Phong Điền'),
(N'Cần Thơ', N'Huyện Thới Lai'),
(N'Hậu Giang', N'Thành phố Vị Thanh'),
(N'Hậu Giang', N'Thành phố Ngã Bảy'),
(N'Hậu Giang', N'Huyện Châu Thành A'),
(N'Hậu Giang', N'Huyện Châu Thành'),
(N'Hậu Giang', N'Huyện Phụng Hiệp'),
(N'Hậu Giang', N'Huyện Vị Thuỷ'),
(N'Hậu Giang', N'Huyện Long Mỹ'),
(N'Hậu Giang', N'Thị xã Long Mỹ'),
(N'Sóc Trăng', N'Thành phố Sóc Trăng'),
(N'Sóc Trăng', N'Huyện Châu Thành'),
(N'Sóc Trăng', N'Huyện Kế Sách'),
(N'Sóc Trăng', N'Huyện Mỹ Tú'),
(N'Sóc Trăng', N'Huyện Cù Lao Dung'),
(N'Sóc Trăng', N'Huyện Long Phú'),
(N'Sóc Trăng', N'Huyện Mỹ Xuyên'),
(N'Sóc Trăng', N'Thị xã Ngã Năm'),
(N'Sóc Trăng', N'Huyện Thạnh Trị'),
(N'Sóc Trăng', N'Thị xã Vĩnh Châu'),
(N'Sóc Trăng', N'Huyện Trần Đề'),
(N'Bạc Liêu', N'Thành phố Bạc Liêu'),
(N'Bạc Liêu', N'Huyện Hồng Dân'),
(N'Bạc Liêu', N'Huyện Phước Long'),
(N'Bạc Liêu', N'Huyện Vĩnh Lợi'),
(N'Bạc Liêu', N'Thị xã Giá Rai'),
(N'Bạc Liêu', N'Huyện Đông Hải'),
(N'Bạc Liêu', N'Huyện Hoà Bình'),
(N'Cà Mau', N'Thành phố Cà Mau'),
(N'Cà Mau', N'Huyện U Minh'),
(N'Cà Mau', N'Huyện Thới Bình'),
(N'Cà Mau', N'Huyện Trần Văn Thời'),
(N'Cà Mau', N'Huyện Cái Nước'),
(N'Cà Mau', N'Huyện Đầm Dơi'),
(N'Cà Mau', N'Huyện Năm Căn'),
(N'Cà Mau', N'Huyện Phú Tân'),
(N'Cà Mau', N'Huyện Ngọc Hiển');


